show tables;

SELECT * FROM wp_commentmeta;
SELECT * FROM wp_comments;
SELECT * FROM wp_links;
SELECT * FROM wp_options;
SELECT * FROM wp_postmeta;
SELECT * FROM wp_posts;
SELECT * FROM wp_sbi_instagram_feeds_posts;
SELECT * FROM wp_sbi_instagram_posts;
SELECT * FROM wp_term_relationships;
SELECT * FROM wp_term_taxonomy;
SELECT * FROM wp_termmeta;
SELECT * FROM wp_terms;
SELECT * FROM wp_tm_taskmeta;
SELECT * FROM wp_tm_tasks;
SELECT * FROM wp_usermeta;
SELECT * FROM wp_users;
SELECT * FROM wp_wfu_dbxqueue;
SELECT * FROM wp_wfu_log;
SELECT * FROM wp_wfu_userdata;
